#!/usr/bin/env python3
"""Export neutral workflow prompts into runtime-specific adapter directories."""

from __future__ import annotations

import argparse
import filecmp
import json
import shutil
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any


# Script flow:
# 1. Load the neutral workflow manifest and requested adapter targets.
# 2. Compare or write workflow content into each runtime-specific adapter target.
# 3. Remove stale mirrored files while preserving allowed source files.
# 4. Report whether generated adapter targets are current.
#
# Function guide:
# - load_manifest/adapters_from_manifest/source_root read manifest configuration.
# - workflow_files/relative_file_set enumerate source and target files.
# - compare_mirror/export_mirror and single-file helpers implement check/write modes.
# - selected_adapters/parse_args/main drive the CLI.
ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "workflows" / "manifest.json"
ALLOWED_SUFFIXES = {".json", ".md"}


@dataclass(frozen=True)
class Adapter:
    id: str
    target_root: Path | None
    target_path: Path | None
    strategy: str


def load_manifest(root: Path) -> dict[str, Any]:
    manifest_path = root / "workflows" / "manifest.json"
    return json.loads(manifest_path.read_text(encoding="utf-8"))


def adapters_from_manifest(root: Path, manifest: dict[str, Any]) -> dict[str, Adapter]:
    adapters: dict[str, Adapter] = {}
    for raw_adapter in manifest.get("generated_adapters", []):
        adapter = Adapter(
            id=raw_adapter["id"],
            target_root=root / raw_adapter["target_root"] if raw_adapter.get("target_root") else None,
            target_path=root / raw_adapter["target_path"] if raw_adapter.get("target_path") else None,
            strategy=raw_adapter.get("strategy", "mirror"),
        )
        adapters[adapter.id] = adapter
    return adapters


def source_root(root: Path, manifest: dict[str, Any]) -> Path:
    return root / manifest["source_root"]


def workflow_files(base: Path) -> list[Path]:
    if not base.exists():
        raise FileNotFoundError(f"workflow source root does not exist: {base}")
    return sorted(
        path
        for path in base.rglob("*")
        if path.is_file() and path.suffix in ALLOWED_SUFFIXES
    )


def relative_file_set(base: Path) -> set[Path]:
    return {path.relative_to(base) for path in workflow_files(base)}


def compare_mirror(source: Path, target: Path) -> list[str]:
    problems: list[str] = []
    source_files = relative_file_set(source)
    target_files = relative_file_set(target) if target.exists() else set()

    for rel_path in sorted(source_files - target_files):
        problems.append(f"missing target file: {target / rel_path}")
    for rel_path in sorted(target_files - source_files):
        problems.append(f"stale target file: {target / rel_path}")
    for rel_path in sorted(source_files & target_files):
        if not filecmp.cmp(source / rel_path, target / rel_path, shallow=False):
            problems.append(f"outdated target file: {target / rel_path}")
    return problems


def export_mirror(source: Path, target: Path) -> list[Path]:
    copied: list[Path] = []
    source_files = relative_file_set(source)
    target_files = relative_file_set(target) if target.exists() else set()

    for rel_path in sorted(source_files):
        source_file = source / rel_path
        target_file = target / rel_path
        target_file.parent.mkdir(parents=True, exist_ok=True)
        if not target_file.exists() or not filecmp.cmp(source_file, target_file, shallow=False):
            shutil.copy2(source_file, target_file)
            copied.append(target_file)

    for rel_path in sorted(target_files - source_files):
        stale = target / rel_path
        stale.unlink()

    prune_empty_dirs(target)
    return copied


def render_copilot_instructions(root: Path, source: Path) -> str:
    prompt_files = [path.relative_to(root).as_posix() for path in workflow_files(source) if path.suffix == ".md"]
    highlighted = [
        "workflows/prompts/multi-agent-repo-review.md",
        "workflows/prompts/task-packet.md",
        "workflows/prompts/verification-sentinel.md",
        "workflows/prompts/tdd/README.md",
        "workflows/prompts/research/README.md",
    ]
    available_highlights = [path for path in highlighted if path in prompt_files]
    lines = [
        "# GitHub Copilot Instructions",
        "",
        "Generated from `workflows/manifest.json` and `workflows/prompts/`.",
        "Do not edit this file directly; run `make prompt-adapters-export`.",
        "",
        "## Repository Workflow",
        "",
        "- Start with `AGENTS.md`, `REVIEW.md`, and `.agent-workflows/README.md` when present.",
        "- Treat documentation impact, tests, receipt evidence, and version impact as part of completion.",
        "- Use task packets for broad requests, backlog rows, issues, or accepted findings before implementation.",
        "- Keep generated or runtime-specific adapter files in sync with the canonical workflow prompt source.",
        "",
        "## Canonical Prompt Entry Points",
        "",
    ]
    lines.extend(f"- `{path}`" for path in available_highlights)
    lines.extend(
        [
            "",
            "## Prompt Source",
            "",
            "The canonical prompt library is under `workflows/prompts/`. Use those files for detailed reviewer, TDD, research, remediation, and verification behavior.",
        ]
    )
    return "\n".join(lines) + "\n"


def compare_single_file(path: Path, expected: str) -> list[str]:
    if not path.exists():
        return [f"missing target file: {path}"]
    try:
        current = path.read_text(encoding="utf-8")
    except OSError as exc:
        return [f"unreadable target file: {path}: {exc}"]
    if current != expected:
        return [f"outdated target file: {path}"]
    return []


def export_single_file(path: Path, content: str) -> list[Path]:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return []
    path.write_text(content, encoding="utf-8")
    return [path]


def prune_empty_dirs(root: Path) -> None:
    if not root.exists():
        return
    for path in sorted((p for p in root.rglob("*") if p.is_dir()), reverse=True):
        try:
            path.rmdir()
        except OSError:
            pass


def selected_adapters(all_adapters: dict[str, Adapter], requested: list[str]) -> list[Adapter]:
    if not requested:
        return list(all_adapters.values())
    unknown = sorted(set(requested) - set(all_adapters))
    if unknown:
        raise ValueError(f"unknown generated adapter(s): {', '.join(unknown)}")
    return [all_adapters[name] for name in requested]


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=ROOT, help="repository root")
    parser.add_argument(
        "--adapter",
        action="append",
        default=[],
        help="adapter id to export or check; repeat for multiple adapters",
    )
    parser.add_argument("--check", action="store_true", help="fail if generated adapters are out of date")
    parser.add_argument("--list", action="store_true", help="list generated and planned adapters")
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    root = args.root.resolve()
    manifest = load_manifest(root)
    source = source_root(root, manifest)
    generated = adapters_from_manifest(root, manifest)

    if args.list:
        for adapter_id in sorted(generated):
            adapter = generated[adapter_id]
            target = adapter.target_root or adapter.target_path
            print(f"{adapter.id}\tgenerated\t{target.relative_to(root)}")
        for adapter in manifest.get("planned_adapters", []):
            print(f"{adapter['id']}\tplanned\t{', '.join(adapter.get('targets', []))}")
        return 0

    try:
        adapters = selected_adapters(generated, args.adapter)
    except ValueError as exc:
        print(str(exc), file=sys.stderr)
        return 2

    failures: list[str] = []
    for adapter in adapters:
        if adapter.strategy == "mirror":
            if not adapter.target_root:
                failures.append(f"{adapter.id}: mirror strategy requires target_root")
                continue
            if args.check:
                failures.extend(f"{adapter.id}: {problem}" for problem in compare_mirror(source, adapter.target_root))
            else:
                copied = export_mirror(source, adapter.target_root)
                print(f"{adapter.id}: exported {len(copied)} changed file(s) to {adapter.target_root.relative_to(root)}")
            continue

        if adapter.strategy == "copilot-instructions":
            if not adapter.target_path:
                failures.append(f"{adapter.id}: copilot-instructions strategy requires target_path")
                continue
            content = render_copilot_instructions(root, source)
            if args.check:
                failures.extend(f"{adapter.id}: {problem}" for problem in compare_single_file(adapter.target_path, content))
            else:
                copied = export_single_file(adapter.target_path, content)
                print(f"{adapter.id}: exported {len(copied)} changed file(s) to {adapter.target_path.relative_to(root)}")
            continue

        else:
            failures.append(f"{adapter.id}: unsupported strategy {adapter.strategy}")
            continue

    if failures:
        print("Generated workflow adapters are out of date:", file=sys.stderr)
        for failure in failures:
            print(f"- {failure}", file=sys.stderr)
        print("Run: python3 scripts/export_workflow_adapters.py", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
